# Site settings
title: Chenchong Charles Zhu
email: chenchong.zhu@gmail.com
url: https://cczhu.github.io
url-pretty: cczhu.github.io
baseurl: ""
description: "Personal website."

# Color settings (hex-codes without the leading hash-tag)
# Sort of based off of
# https://color.adobe.com/Blue-Space-color-theme-1941412/edit/?copy=true&base=2&rule=Custom&selected=2&name=Copy%20of%20Blue%20Space&mode=rgb&rgbvalues=0.10980392156862745,0.10196078431372549,0.17254901960784313,0.1845248128720041,0.1836949610108547,0.27,0.4358358255727076,0.7917235546126449,1,0.7341530941575047,0.6345617824540357,0.78,0.9764705882352941,0.8,0.14901960784313725&swatchOrder=0,1,2,3,4
color:
  primary-dark: "#2F2F45"
  navbar: "#1C1A2C"
  navbar-text: "#4FBFFF"  # hover/focus/active needs rgba, so manually change those to rgba(79, 191, 255, .2)
  navbar-title: "#F9CC26"
  navbar-blog: "#E4C3F4"
  post-subhead: "#E4C3F4"
  text: "#FFFFFF"
  links: "#4FBFFF"
  headers: "#4FBFFF"
  hover: "#F9CC26"  # Except for picture links.
  code-block: "#49483E"
  page-header: "#FFFFFF"
  footer: "#1C1A2C"
  footer-text: "#BBA2C7"
  footer-link: "#4FBFFF"

fonts:
  main: "'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif"
  headers: "'Montserrat', 'Helvetica Neue', Helvetica, Arial, sans-serif"
  navbar: "'Montserrat', 'Helvetica Neue', Helvetica, Arial, sans-serif"

# navbar-col: "#1C1A2C" #"#100E1C"
# navbar-border-col: "#FFFFFF"
# navbar-title-col: "#F9CC26"
# navbar-text-col: "#4FBFFF"
# navbar-blog-col: "#E4C3F4"
# navbar-children-col: "#1C1A2C"
# page-col: "#2F2F45" #"#1C1A2C" "#191D2B"
# page-text-col: "#FFFFFF"
# link-col: "#4FBFFF"
# hover-col: "#F9CC26" #"#f97a26"
# post-head-col: "#4FBFFF"
# post-subhead-col: "#BBA2C7"
# footer-col: "#1C1A2C"
# footer-text-col: "#BBA2C7"
# footer-link-col: "#4FBFFF"

# Navbar settings
navbar-links:
  About: "#about"
  Projects: "#projects"
  Contact: "#contact"
  Blog: "/blog"

# Footer settings
footer: Your Website

author:
  name: Charles Zhu

timezone: "America/Toronto"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/ChenchongZ
  - title: github
    url: https://github.com/cczhu/

social-network-links:
  email: "chenchong.zhu@gmail.com"
  github: cczhu
  twitter: ChenchongZ

# Manual display + ordering of projects.  TODO: figure out if we can just use the name rather than this redundant list
projects:
  DeepMoon: "deepmoon"
  Baseband: "baseband"
  Mergers: "mergers"

# Build settings
permalink: /:year-:month-:day-:title/
ymarkdown: kramdown

# Syntax highlighter
highlighter: rouge

kramdown:
  input: GFM

# Paginator settings
paginate: 5
paginate_path: "blog/page:num/"
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      social-share: true # add social media sharing buttons to all blog posts

# Use tags index page and make tags on each post clickable
link-tags: false

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - jekyll_notes.md

# Plugins
plugins:
  - jekyll-paginate